FROM golang:1.19-alpine AS builder
RUN apk update && apk add --no-cache make git
WORKDIR /
RUN git clone https://github.com/smk762/callisto -b cosmos/v0.46.x
WORKDIR /callisto
RUN go mod download
RUN make build

FROM alpine:latest
WORKDIR /bdjuno
COPY --from=builder /callisto/build/bdjuno /usr/bin/bdjuno
RUN bdjuno init
CMD [ "bdjuno" ]